export const PROJECT_STATUS_MAP = {
  PENDING: "Pending",
  IN_PROGRESS: "In Progress",
  PAUSED: "Paused",
  COMPLETED: "Completed",
};

export const PROJECT_STATUS_LIST = [
  { label: PROJECT_STATUS_MAP.PENDING, value: PROJECT_STATUS_MAP.PENDING },
  { label: PROJECT_STATUS_MAP.IN_PROGRESS, value: PROJECT_STATUS_MAP.IN_PROGRESS },
  { label: PROJECT_STATUS_MAP.PAUSED, value: PROJECT_STATUS_MAP.PAUSED },
  { label: PROJECT_STATUS_MAP.COMPLETED, value: PROJECT_STATUS_MAP.COMPLETED },
];
